### ISSUE TITLE
DBIRTH and DDATA

### ISSUE THREAD

**Issue by Voxifer** [mkeras/EmbeddedSparkplugNode#2]
I understand that the library is still on devlelping stage, but I was wondering if there's any new version where DBIRTH and DDATA topics are implemented?

**Comment by Voxifer** [comment]
I'm planning to try to dig deeper to the library and implement it myself, but I wouldn't want to do something that has already been implemented. So that's why I'm wondering if anything was done regarding it. Thanks!

**Comment by mkeras** [comment]
I have not yet gotten that far, I have a rough idea of how I would implement it, but nothing concrete yet.
My implementation would include some updates to the BasicTag library, specifically changing some of the backend for iterating and grouping tags, to enable independent tag groups for creating Devices.
