### ISSUE TITLE
Decode sparkplug subscribe callback Example

### ISSUE THREAD

**Issue by NathanM-Vertiv** [mkeras/EmbeddedSparkplugNode#4]
when I get a payload back from a subscribed tag, it is encoded with Sparkplug, I can't find a way to decode this in Arduino. This Library looks like it potentially supports this, but I can only see publishing in the example, could you confirm if this is possible with this library and maybe point me in the right direction. Thanks.

**Comment by mkeras** [comment]
Hi, the sparkplug standard is not native to Arduino, it is an open standard generally used in industrial scenarios. I am working on making a full tutorial, that I will share as soon as it's finished.

In short, this library is designed to be used with a software that has sparkplug/mqtt functionality built in. The software I use is called ignition by inductive automation: https://inductiveautomation.com/ignition/

In the meantime, this video gives a good explanation of sparkplug:
https://www.youtube.com/watch?v=-9vMAe7P25A

Any more questions you have would be helpful, as it will help me create a good tutorial!

**Comment by NathanM-Vertiv** [comment]
Hi thanks for getting back to me, I am using Ignition also and I am very familiar with it, but my C knowledge is very lacking.

I am looking to read a tag from my Ignition Distributor Module with an esp32, which I can do, but it just returns the encoded byte array. I am struggling with how to decode this into the individual metric values.

**Comment by mkeras** [comment]
Ok, I think I understand now.
Currently decoding is handled by this function: `SparkplugNodeState processIncomingNCMDPayload(SparkplugNodeConfig* node, uint8_t* buffer, size_t length);`

In the current implementation, it doesn't give access to the decoded metrics, but rather automatically writes the incoming metric values directly to a BasicTag that matches the incoming metric alias or name. The BasicTag will only be written to if the remote_writable flag is set to true when it is created. Metrics that don't match any BasicTag are ignored.

If you need to access the metrics themselves for some other purpose, I can make note for the next update to the library.

Let me know if this helps or not, I can go into more detail and share some examples if you like.

**Comment by NathanM-Vertiv** [comment]
Thanks, I was able to find a setting in Ignition to change the 'Data Format Type' from Sparkplug protobuf, to Sparkplug JSON, so I am able to just read it as a json string instead of needing to decode.

Let me know once the tutorial goes up and I'll check it out.

**Comment by mkeras** [comment]
Awesome, I will let you know when it does, for now I'm closing this issue.
